HSC_Report3/Controllers/HSC_RecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HSC_Report3;

namespace HSC_Report3.Controllers
{
    public class HSC_RecordController : Controller
    {
        private studInfoEntities db = new studInfoEntities();

        // GET: HSC_Record
        public ActionResult Index()
        {
            return View(db.HSC_Record.ToList());
        }

        // GET: HSC_Record/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HSC_Record hSC_Record = db.HSC_Record.Find(id);
            if (hSC_Record == null)
            {
                return HttpNotFound();
            }
            
            return View(hSC_Record);
        }
        

        // GET: HSC_Record/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HSC_Record/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "seatNo,FirstName,LasttName,Math,English,Physics,Chemistry,Computer")] HSC_Record hSC_Record)
        {
            if (ModelState.IsValid)
            {
                db.HSC_Record.Add(hSC_Record);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hSC_Record);
        }

        // GET: HSC_Record/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HSC_Record hSC_Record = db.HSC_Record.Find(id);
            if (hSC_Record == null)
            {
                return HttpNotFound();
            }
            return View(hSC_Record);
        }

        // POST: HSC_Record/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "seatNo,FirstName,LasttName,Math,English,Physics,Chemistry,Computer")] HSC_Record hSC_Record)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hSC_Record).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hSC_Record);
        }

        // GET: HSC_Record/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HSC_Record hSC_Record = db.HSC_Record.Find(id);
            if (hSC_Record == null)
            {
                return HttpNotFound();
            }
            return View(hSC_Record);
        }

        // POST: HSC_Record/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HSC_Record hSC_Record = db.HSC_Record.Find(id);
            db.HSC_Record.Remove(hSC_Record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        /*public ActionResult ReceiveWithRequestForm()
        {
            return View();
        }*/

        [HttpPost]
        public ActionResult ReceiveWithRequestFormData()
        {
            string id = Request.Form["txtSeatNo"];
            //HSC_Record id1 = db.HSC_Record.Find(id);
            HSC_Record avg = db.HSC_Record.Find(id);
            List<float> sum = new List<float>();
            sum.Add((float)avg.English);
            sum.Add((float)avg.Math);
            sum.Add((float)avg.Computer);
            sum.Add((float)avg.Chemistry);
            sum.Add((float)avg.Physics);
            float add = 0;
            for (int i = 0; i < 5; i++)
            {
                add = add + (float)sum[i];
            }

            ViewBag.addition = add;
            float Average = add / 5;
            ViewBag.Average = Average;
            int flag = 0;
            if(Average >= 35)
            {
                flag=1;
            }
            if (flag == 1)
            {
                ViewBag.Pass = "Pass";
            }
            else
            {
                ViewBag.Pass = "Fail";
            }
            return View(avg);
        }
    }
}

HSC_Report3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;


namespace HSC_Report3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HSC_Report3/Views/HSC_Record/Create.cshtml
@model HSC_Report3.HSC_Record

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HSC_Record</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.seatNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.seatNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.seatNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LasttName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LasttName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LasttName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Math, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Math, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Math, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.English, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.English, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.English, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Physics, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Physics, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Physics, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chemistry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chemistry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Chemistry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Computer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Computer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Computer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HSC_Report3/Views/HSC_Record/Delete.cshtml
@model HSC_Report3.HSC_Record

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HSC_Record</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LasttName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LasttName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Math)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Math)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.English)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.English)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Physics)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Physics)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chemistry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chemistry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Computer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Computer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HSC_Report3/Views/HSC_Record/Details.cshtml
@model HSC_Report3.HSC_Record

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HSC_Record</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LasttName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LasttName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Math)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Math)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.English)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.English)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Physics)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Physics)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chemistry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chemistry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Computer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Computer)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.seatNo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HSC_Report3/Views/HSC_Record/Edit.cshtml
@model HSC_Report3.HSC_Record

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HSC_Record</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.seatNo)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LasttName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LasttName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LasttName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Math, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Math, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Math, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.English, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.English, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.English, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Physics, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Physics, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Physics, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chemistry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chemistry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Chemistry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Computer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Computer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Computer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HSC_Report3/Views/HSC_Record/Index.cshtml
@model IEnumerable<HSC_Report3.HSC_Record>

@{
    ViewBag.Title = "Index";
}

<h2>Enter Student Data Here</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-dark" style="border:1px">
    <tr class="success">
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LasttName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Math)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.English)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Physics)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Chemistry)
        </th>
        <th >
            @Html.DisplayNameFor(model => model.Computer)
        </th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="info">
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.LasttName)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.Math)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.English)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.Physics)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.Chemistry)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.Computer)
            </td>
            <td class="info">
                @Html.ActionLink("Edit", "Edit", new { id = item.seatNo }) |
                @Html.ActionLink("Details", "Details", new { id = item.seatNo }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.seatNo })

            </td>
        </tr>
    }

</table>

HSC_Report3/Views/HSC_Record/ReceiveWithRequestFormData.cshtml
@model HSC_Report3.HSC_Record

@{
    ViewBag.Title = "Receive with request form data";
}

<h2>Report</h2>


<div>
    <h4>@Html.DisplayFor(model => model.FirstName)&nbsp;&nbsp;@Html.DisplayFor(model => model.LasttName) HSC Report</h4>
    <hr />
    <dl class="dl-vertical">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <hr />

        <dt>
            @Html.DisplayNameFor(model => model.LasttName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LasttName)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Math)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Math)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.English)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.English)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Physics)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Physics)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Chemistry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chemistry)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Computer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Computer)
        </dd>
        <hr id="hr" />
    </dl>
</div>
<strong>Percentage:      </strong>@ViewBag.Average%
<br />
<strong>Result:      </strong>@ViewBag.Pass
<br />
<br />
<div>
    <input  type="button" value="Print" id="btn-print" />
</div>

HSC_Report3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HSC_Report3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HSC_Report3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/mycss.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

</head>


<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6"><img src="~/Images/document-clipart-report-2.png" height="500px" width="500"/></div>
            <div class="col-md-6">
                @using (Html.BeginForm("ReceiveWithRequestFormData", "HSC_Record"))
                {
                    <div class="form-group">
                        <br />
                        @Html.Label("Seat Number")<br />
                        @Html.TextBox("txtSeatNo", "h1")<br />
                        <br />
                        <input class="btn btn-warning" type="submit" value="Report" style="border-color:orangered"/>
                    </div>
                }
            </div>
        </div>
    </div> 
</body>
</html>

HSC_Report3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    

</head>
<body>
    <!--*****************************************************************************************-->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @Html.ActionLink("Student Report", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Database", "Index", "HSC_Record")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <!--*****************************************************************************************-->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>